# Generated by Django 2.0.4 on 2018-04-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jungle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='growprofile',
            name='plant_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
