# Generated by Django 2.0.4 on 2018-04-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jungle', '0002_growprofile_plant_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='growprofile',
            name='name',
            field=models.CharField(default='N/A', max_length=25),
            preserve_default=False,
        ),
    ]
