# Generated by Django 2.0.4 on 2018-04-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jungle', '0003_growprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growprofile',
            name='plant_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
